In [94]:
from pytuning.scales import *
from sympy import *
import numpy as np

## Scale Similarity among Different Intonation Systems

Now that we have methods for obtaining the pitch names and fundamental frequencies associated with a scale in a snippet of audio, to compute a labeling, we have to come up with some measure of similarity among different intonation systems. The idea is once we have this mathematical measure, then we label the scale as the intonation system with the highest similarity. 

To approach this task, we need functions to create equal-temperament, Pythagorean, and Just scale templates. 

### Equal Temperament

In [85]:
edo_scale = create_edo_scale(12)
edo_scale

[1,
 2**(1/12),
 2**(1/6),
 2**(1/4),
 2**(1/3),
 2**(5/12),
 sqrt(2),
 2**(7/12),
 2**(2/3),
 2**(3/4),
 2**(5/6),
 2**(11/12),
 2]

<font color='red'> for these scale creation functions, not sure if it's worth converting the sympy rationals to floats throughout the array as I'm currently doing. 

In [104]:
edo_scale_float = [i.evalf() for i in edo_scale]
edo_scale_float

[1.00000000000000,
 1.05946309435930,
 1.12246204830937,
 1.18920711500272,
 1.25992104989487,
 1.33483985417003,
 1.41421356237310,
 1.49830707687668,
 1.58740105196820,
 1.68179283050743,
 1.78179743628068,
 1.88774862536339,
 2.00000000000000]

In [112]:
def create_edo_template(ref_pitch):
    edo_scale = create_edo_scale(12)
    edo_scale_float = [i.evalf() for i in edo_scale]

    return ref_pitch * np.array(edo_scale_float)

In [115]:
ref_pitch = 220
create_edo_template(ref_pitch)

array([220.000000000000, 233.081880759045, 246.941650628062,
       261.625565300599, 277.182630976872, 293.664767917408,
       311.126983722081, 329.627556912870, 349.228231433004,
       369.994422711634, 391.995435981749, 415.304697579945,
       440.000000000000], dtype=object)

### Just

<font color='red'> still haven't figured out what the 'proper' just ratios are. Will need to ask someone for guidance. Looks like there isn't one right answer. For now, just going to hardcode the ratios. 

In [78]:
import sympy as sp
harmonic_scale = [sp.Integer(1), sp.Rational(25, 24), sp.Rational(9,8), sp.Rational(6,5), 
                  sp.Rational(5,4), sp.Rational(4, 3), sp.Rational(45, 32), sp.Rational(3,2), 
                  sp.Rational(8,5), sp.Rational(5,3), sp.Rational(9,5), sp.Rational(15,8),
                                                                                 sp.Integer(2)]
harmonic_scale

[1, 25/24, 9/8, 6/5, 5/4, 4/3, 45/32, 3/2, 8/5, 5/3, 9/5, 15/8, 2]

In [117]:
def create_just_template(ref_pitch):
    just_scale = [sp.Integer(1), sp.Rational(25, 24), sp.Rational(9,8), sp.Rational(6,5), 
                  sp.Rational(5,4), sp.Rational(4, 3), sp.Rational(45, 32), sp.Rational(3,2), 
                  sp.Rational(8,5), sp.Rational(5,3), sp.Rational(9,5), sp.Rational(15,8),
                                                                                 sp.Integer(2)]
    just_scale_float = [i.evalf() for i in just_scale]

    return ref_pitch * np.array(just_scale_float)

In [118]:
create_just_template(ref_pitch)

array([220.000000000000, 229.166666666667, 247.500000000000,
       264.000000000000, 275.000000000000, 293.333333333333,
       309.375000000000, 330.000000000000, 352.000000000000,
       366.666666666667, 396.000000000000, 412.500000000000,
       440.000000000000], dtype=object)

In [59]:
# i = 1
# j = 1

# scale = create_harmonic_scale(i, j)
# target = [1, 25/24, 9/8, 6/5, 5/4, 4/3, 45/32, 3/2, 8/5, 5/3, 9/5, 15/8, 2]

# # for i in range(5):
# #     for j in range(50):
# #         scale = create_harmonic_scale(i, j)
# #         if scale == target and len(scale) == 13:
# #             print(scale)
# #             break

# # # while scale != target and len(scale) < 13 and i < 100 and j < 100:
# # #     i += 1
# # #     j += 1
# # #     scale = create_harmonic_scale(i, j)
# # #     # if len(scale) > 13: 
# # #     #     break
# print('i = ', i, 'j = ', j)
# print(scale)
# len(scale)

### Pythagorean

In [19]:
scale = create_pythagorean_scale()
scale

[1,
 256/243,
 9/8,
 32/27,
 81/64,
 4/3,
 1024/729,
 3/2,
 128/81,
 27/16,
 16/9,
 243/128,
 2]

In [119]:
def create_pythagorean_template(ref_pitch):
    pythagorean_scale = create_pythagorean_scale()
    pythagorean_scale_float = [i.evalf() for i in pythagorean_scale]

    return ref_pitch * np.array(pythagorean_scale_float)

In [120]:
create_pythagorean_template(ref_pitch)

array([220.000000000000, 231.769547325103, 247.500000000000,
       260.740740740741, 278.437500000000, 293.333333333333,
       309.026063100137, 330.000000000000, 347.654320987654,
       371.250000000000, 391.111111111111, 417.656250000000,
       440.000000000000], dtype=object)

In [121]:
def create_scale_template(ref_pitch, scale):
    '''
    Creates a template for given scale based on reference pitch. 
    Scale: 'just', 'edo', 'pythagorean'
    '''
    if scale == 'just':
        return create_just_template(ref_pitch)
    if scale == 'edo':
        return create_edo_template(ref_pitch)
    if scale == 'pythagorean':
        return create_pythagorean_template(ref_pitch)
    
    else:
        return 'unrecognized scale'

In [130]:
print('Just: ', create_scale_template(ref_pitch, 'just'))
print('Equal Temperament: ', create_scale_template(ref_pitch, 'edo'))
print('Pythagorean: ', create_scale_template(ref_pitch, 'pythagorean'))

Just:  [220.000000000000 229.166666666667 247.500000000000 264.000000000000
 275.000000000000 293.333333333333 309.375000000000 330.000000000000
 352.000000000000 366.666666666667 396.000000000000 412.500000000000
 440.000000000000]
Equal Temperament:  [220.000000000000 233.081880759045 246.941650628062 261.625565300599
 277.182630976872 293.664767917408 311.126983722081 329.627556912870
 349.228231433004 369.994422711634 391.995435981749 415.304697579945
 440.000000000000]
Pythagorean:  [220.000000000000 231.769547325103 247.500000000000 260.740740740741
 278.437500000000 293.333333333333 309.026063100137 330.000000000000
 347.654320987654 371.250000000000 391.111111111111 417.656250000000
 440.000000000000]


## Comparing Scales

In [60]:
from pytuning.scales import create_edo_scale, create_pythagorean_scale
from pytuning.utilities import compare_two_scales
scale_1 = create_edo_scale(12)
scale_2 = create_pythagorean_scale()
compare_two_scales(scale_1, scale_2, title=['12-TET', 'Pythagorean'])

               12-TET           Pythagorean
     Cents       Freq      Cents       Freq  Delta(Cents)
 =========  =========  =========  =========  ============
    0.0000   220.0000     0.0000   220.0000        0.0000
  100.0000   233.0819    90.2250   231.7695        9.7750
  200.0000   246.9417   203.9100   247.5000       -3.9100
  300.0000   261.6256   294.1350   260.7407        5.8650
  400.0000   277.1826   407.8200   278.4375       -7.8200
  500.0000   293.6648   498.0450   293.3333        1.9550
  600.0000   311.1270   588.2700   309.0261       11.7300
  700.0000   329.6276   701.9550   330.0000       -1.9550
  800.0000   349.2282   792.1800   347.6543        7.8200
  900.0000   369.9944   905.8650   371.2500       -5.8650
 1000.0000   391.9954   996.0900   391.1111        3.9100
 1100.0000   415.3047  1109.7750   417.6562       -9.7750
 1200.0000   440.0000  1200.0000   440.0000        0.0000


In [70]:
create_harmonic_scale(1, 23)

[1, 17/16, 9/8, 19/16, 5/4, 21/16, 11/8, 23/16, 3/2, 13/8, 7/4, 15/8, 2]

In [79]:
scale_1 = create_edo_scale(12)
scale_2 = harmonic_scale
compare_two_scales(scale_1, scale_2, title=['12-TET', 'Harmonic'])

               12-TET              Harmonic
     Cents       Freq      Cents       Freq  Delta(Cents)
 =========  =========  =========  =========  ============
    0.0000   220.0000     0.0000   220.0000        0.0000
  100.0000   233.0819    70.6724   229.1667       29.3276
  200.0000   246.9417   203.9100   247.5000       -3.9100
  300.0000   261.6256   315.6413   264.0000      -15.6413
  400.0000   277.1826   386.3137   275.0000       13.6863
  500.0000   293.6648   498.0450   293.3333        1.9550
  600.0000   311.1270   590.2237   309.3750        9.7763
  700.0000   329.6276   701.9550   330.0000       -1.9550
  800.0000   349.2282   813.6863   352.0000      -13.6863
  900.0000   369.9944   884.3587   366.6667       15.6413
 1000.0000   391.9954  1017.5963   396.0000      -17.5963
 1100.0000   415.3047  1088.2687   412.5000       11.7313
 1200.0000   440.0000  1200.0000   440.0000        0.0000


In [83]:
scale_1 = harmonic_scale
scale_2 = create_pythagorean_scale()

compare_two_scales(scale_1, scale_2, title=['Harmonic', 'Pythagorean'])

             Harmonic           Pythagorean
     Cents       Freq      Cents       Freq  Delta(Cents)
 =========  =========  =========  =========  ============
    0.0000   220.0000     0.0000   220.0000        0.0000
   70.6724   229.1667    90.2250   231.7695      -19.5526
  203.9100   247.5000   203.9100   247.5000        0.0000
  315.6413   264.0000   294.1350   260.7407       21.5063
  386.3137   275.0000   407.8200   278.4375      -21.5063
  498.0450   293.3333   498.0450   293.3333        0.0000
  590.2237   309.3750   588.2700   309.0261        1.9537
  701.9550   330.0000   701.9550   330.0000        0.0000
  813.6863   352.0000   792.1800   347.6543       21.5063
  884.3587   366.6667   905.8650   371.2500      -21.5063
 1017.5963   396.0000   996.0900   391.1111       21.5063
 1088.2687   412.5000  1109.7750   417.6562      -21.5063
 1200.0000   440.0000  1200.0000   440.0000        0.0000
